insert into SUBSCRIPTION (SUBSCRIPTION_ID,SUBSCRIBER_NAME, DATE_SUBSCRIBED, DATE_RETURNED, BOOK_ID)values(2,'Mark',TO_DATE('26-04-2020','dd-MM-yyyy'),TO_DATE('14-05-2020','dd-MM-yyyy'),'B4232');

insert into SUBSCRIPTION (SUBSCRIPTION_ID,SUBSCRIBER_NAME, DATE_SUBSCRIBED, DATE_RETURNED, BOOK_ID) values(3,'Peter',TO_DATE('22-06-2020','dd-MM-yyyy'),null,'B1212');

insert into SUBSCRIPTION (SUBSCRIPTION_ID,SUBSCRIBER_NAME, DATE_SUBSCRIBED, DATE_RETURNED, BOOK_ID)values(1,'John', TO_DATE('12-06-2020','dd-MM-yyyy'),null, 'B1212');